var group1 = [];
var group2 = [];
var group3 = [];
var group4 = [];
var group5 = [];
var group6 = [];
var group7 = [];
var group8 = [];
var group9 = [];
var group10 = [];

for(var i = 0; i < 6; i++) {
  group1.push("Person");
  group2.push("Person");
  group3.push("Person");
  group4.push("Person");
  group5.push("Person");
  group6.push("Person");
  group7.push("Person");
  group8.push("Person");
  group9.push("Person");
  group10.push("Person");
}

groups = [];
groups.push(group1);
groups.push(group2);
groups.push(group3);
groups.push(group4);
groups.push(group5);
groups.push(group6);
groups.push(group7);
groups.push(group8);
groups.push(group9);
groups.push(group10);

var currentActivePerson = "";
currentActivePersonName = "";
var currentActiveGroup = 0;

var questions = [
  "Your Information Visualization skills?",
  "Your statistical skills?",
  "Your mathematics skills?",
  "Your drawing and artistic skills?",
  "Your computer usage skills?",
  "Your programming skills?",
  "Your graphics programming skills?",
  "Your HCI programming skills?",
  "Your user experience evaluation skills?",
  "Your communication skills?",
  "Your collaboration skills?",
  "Your code repository skills?",
  "What do you expect to learn in Information Visualization? How do expect to use what you learn?",
  "Please, tell me about yourself. What interest you? Do you have any hobbies?"
];

var data = [
  {
    "Timestamp": "2019-01-15T14:44:53.162Z",
    "name": "Hannah Abbott ",
    "major": "Computer Science",
    "pursuingDegree": "Bachelor in Science",
    "interests": "I'm interested in visualization because it allows us to gain insight from complex and large data sets. I like skiing, hiking, and music.",
    "expectations": "Be able to tell a story through data driven document.",
    "visualizationskill": 4,
    "statisticalskill": 3,
    "mathematicsskill": 6,
    "artisticskill": 2,
    "computerskill": 6,
    "programmingskill": 5,
    "graphicsprogrammingskill": 3,
    "hciskill": 4,
    "evaluationskill": 1,
    "communicationskill": 4,
    "collaborationskill": 3,
    "repositoryskill": 5
  },
  {
    "Timestamp": "2019-01-15T15:20:11.088Z",
    "name": "Ludo Bagman ",
    "major": "Machine Learning",
    "pursuingDegree": "Master in Science",
    "interests": "Going to the gym",
    "expectations": "I wish to learn and be proficient at relevant and useful visualization tools and methods in order to be able to create vizualisations in projects and future work. ",
    "visualizationskill": 1,
    "statisticalskill": 5,
    "mathematicsskill": 5,
    "artisticskill": 1,
    "computerskill": 7,
    "programmingskill": 8,
    "graphicsprogrammingskill": 3,
    "hciskill": 2,
    "evaluationskill": 1,
    "communicationskill": 10,
    "collaborationskill": 8,
    "repositoryskill": 7
  },
  {
    "Timestamp": "2019-01-15T15:21:11.113Z",
    "name": "Bathilda Bagshot ",
    "major": "Engineering Physics",
    "pursuingDegree": "Bachelor in Science",
    "interests": "I am an Erasmus exchange student from Istanbul Technical University. I am studying Engineering Physics but I have a huge interest in programming and data science. I am taking half of my courses in machine learning, data science and artificial intelligence fields. I am familiar with Photoshop and Illustrator, done some poster works with them in the past. I like minimalist designs and making them avant-garde.",
    "expectations": "Representing data in a meaningful way and making understandable for everyone. Also the methods and concepts for different types of data structres.",
    "visualizationskill": 6,
    "statisticalskill": 5,
    "mathematicsskill": 5,
    "artisticskill": 3,
    "computerskill": 10,
    "programmingskill": 7,
    "graphicsprogrammingskill": 4,
    "hciskill": 6,
    "evaluationskill": 4,
    "communicationskill": 10,
    "collaborationskill": 7,
    "repositoryskill": 5
  },
  {
    "Timestamp": "2019-01-15T15:27:37.975Z",
    "name": "Katie Bell ",
    "major": "Computer Science, Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "Games, art",
    "expectations": "I expect to learn how to design an interactive graphics s.t. it is easy for the user to understand and guide through. I expect to use it to present data to the user e.g. game stats, food choices and interactive museums.",
    "visualizationskill": 2,
    "statisticalskill": 2,
    "mathematicsskill": 4,
    "artisticskill": 7,
    "computerskill": 6,
    "programmingskill": 3,
    "graphicsprogrammingskill": 2,
    "hciskill": 2,
    "evaluationskill": 4,
    "communicationskill": 7,
    "collaborationskill": 5,
    "repositoryskill": 2
  },
  {
    "Timestamp": "2019-01-15T15:32:37.639Z",
    "name": "Cuthbert Binns",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "I enjoy doodling and bullet journaling, dancing and playing the badminton.",
    "expectations": "I want to acquire the skills of making informative and interactive visualizations, and would also like to add some information visualization projects to my portfolio. ",
    "visualizationskill": 5,
    "statisticalskill": 5,
    "mathematicsskill": 5,
    "artisticskill": 3,
    "computerskill": 7,
    "programmingskill": 7,
    "graphicsprogrammingskill": 2,
    "hciskill": 3,
    "evaluationskill": 1,
    "communicationskill": 4,
    "collaborationskill": 5,
    "repositoryskill": 7
  },
  {
    "Timestamp": "2019-01-15T16:50:02.663Z",
    "name": "Phineas Nigellus Black",
    "major": "Human-Computer Interaction",
    "pursuingDegree": "Master in Science",
    "interests": "Film, music videos, skiing",
    "expectations": "I don’t really know yet.",
    "visualizationskill": 4,
    "statisticalskill": 5,
    "mathematicsskill": 6,
    "artisticskill": 7,
    "computerskill": 6,
    "programmingskill": 3,
    "graphicsprogrammingskill": 2,
    "hciskill": 5,
    "evaluationskill": 7,
    "communicationskill": 10,
    "collaborationskill": 8,
    "repositoryskill": 6
  },
  {
    "Timestamp": "2019-01-15T17:04:31.128Z",
    "name": "Sirius Black",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "I'm interested in machine learning, graphics and visualization. I do also make computer games as a hobby.",
    "expectations": "I hope to somehow be able to apply it in conjunction with machine learning (perhaps using it to visualize machine learning data or decision making). Mostly though, it just seemed like a generally useful skill to have.",
    "visualizationskill": 2,
    "statisticalskill": 2,
    "mathematicsskill": 4,
    "artisticskill": 8,
    "computerskill": 7,
    "programmingskill": 5,
    "graphicsprogrammingskill": 4,
    "hciskill": 3,
    "evaluationskill": 2,
    "communicationskill": 4,
    "collaborationskill": 5,
    "repositoryskill": 4
  },
  {
    "Timestamp": "2019-01-15T17:15:02.075Z",
    "name": "Amelia Bones ",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "Gym, baking cakes, socialize with friends.",
    "expectations": "I expect to learn how to visualize information in good and handy ways. Hopefully I can use my new learnings in some other projects and eventually in my future career.",
    "visualizationskill": 3,
    "statisticalskill": 2,
    "mathematicsskill": 5,
    "artisticskill": 5,
    "computerskill": 6,
    "programmingskill": 2,
    "graphicsprogrammingskill": 1,
    "hciskill": 1,
    "evaluationskill": 3,
    "communicationskill": 8,
    "collaborationskill": 7,
    "repositoryskill": 3
  },
  {
    "Timestamp": "2019-01-15T17:30:09.557Z",
    "name": "Susan Bones ",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Football, Youtube",
    "expectations": "I would like to create clear and fancy visulaizations of the data that I analyse and process. So I expect to learn how to be clear and efficient.",
    "visualizationskill": 2,
    "statisticalskill": 6,
    "mathematicsskill": 8,
    "artisticskill": 2,
    "computerskill": 6,
    "programmingskill": 4,
    "graphicsprogrammingskill": 2,
    "hciskill": 2,
    "evaluationskill": 3,
    "communicationskill": 7,
    "collaborationskill": 6,
    "repositoryskill": 5
  },
  {
    "Timestamp": "2019-01-15T17:44:49.049Z",
    "name": "Terry Boot",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "Music, dance",
    "expectations": "How to, in a efficient way, visualize data. How to do that interactively rather than relying on things like infographics where the creator chooses what data to show instead of the user.",
    "visualizationskill": 7,
    "statisticalskill": 6,
    "mathematicsskill": 5,
    "artisticskill": 4,
    "computerskill": 10,
    "programmingskill": 8,
    "graphicsprogrammingskill": 1,
    "hciskill": 3,
    "evaluationskill": 2,
    "communicationskill": 10,
    "collaborationskill": 3,
    "repositoryskill": 8
  },
  {
    "Timestamp": "2019-01-15T18:11:01.025Z",
    "name": "Lavender Brown",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "I am interested in sports (preferably hockey followed by soccer) and music.",
    "expectations": "I expect to learn how to use data and present it in a way so that it makes sense to other people.",
    "visualizationskill": 2,
    "statisticalskill": 4,
    "mathematicsskill": 5,
    "artisticskill": 2,
    "computerskill": 7,
    "programmingskill": 3,
    "graphicsprogrammingskill": 1,
    "hciskill": 3,
    "evaluationskill": 4,
    "communicationskill": 10,
    "collaborationskill": 9,
    "repositoryskill": 4
  },
  {
    "Timestamp": "2019-01-15T18:26:29.705Z",
    "name": "Millicent Bulstrode",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "",
    "expectations": "I expect that I'll get knowledge about what different visualisation tools that exist as well as what one should think about when visualising data. Hopefully in my future work.",
    "visualizationskill": 2,
    "statisticalskill": 3,
    "mathematicsskill": 10,
    "artisticskill": 8,
    "computerskill": 10,
    "programmingskill": 7,
    "graphicsprogrammingskill": 2,
    "hciskill": 6,
    "evaluationskill": 2,
    "communicationskill": 10,
    "collaborationskill": 7,
    "repositoryskill": 8
  },
  {
    "Timestamp": "2019-01-15T19:07:25.032Z",
    "name": "Charity Burbage",
    "major": "Media Technology",
    "pursuingDegree": "Master in Computer Science with specialization in Interactive Media Technology",
    "interests": "I'm big into football. In the Swedish league Allsvenskan I follow AIK, but I also follow English club Liverpool FC tirelessly. About a year ago, I also picked up playing the guitar which has turned out to be a great hobby for me. ",
    "expectations": "To transform big datasets retrieved from somewhere on the web into some sort of visualization of the dataset. ",
    "visualizationskill": 2,
    "statisticalskill": 4,
    "mathematicsskill": 7,
    "artisticskill": 3,
    "computerskill": 7,
    "programmingskill": 6,
    "graphicsprogrammingskill": 2,
    "hciskill": 5,
    "evaluationskill": 6,
    "communicationskill": 9,
    "collaborationskill": 10,
    "repositoryskill": 6
  },
  {
    "Timestamp": "2019-01-15T19:40:34.613Z",
    "name": "Frank Bryce",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "I'm a media technology student with interests in web design/development, video, photography and graphics. In my spare time I like spending time learning graphic design, motion graphics and to become a better web designer/developer. Moreover I enjoy photography, sports and watching movies. ",
    "expectations": "To learn about theories and techniques behind information visualization to be able to create interactive programs for presenting data. I think this knowledge can be useful in many different situations i.e to analyze statistics and keep track of sales, especially today with big data.",
    "visualizationskill": 2,
    "statisticalskill": 2,
    "mathematicsskill": 4,
    "artisticskill": 2,
    "computerskill": 6,
    "programmingskill": 3,
    "graphicsprogrammingskill": 1,
    "hciskill": 2,
    "evaluationskill": 3,
    "communicationskill": 7,
    "collaborationskill": 3,
    "repositoryskill": 4
  },
  {
    "Timestamp": "2019-01-15T21:51:57.131Z",
    "name": "Alecto Carrow",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "Computer games, working out, padle",
    "expectations": "How to handle and use big amounts of data to explain things.",
    "visualizationskill": 1,
    "statisticalskill": 3,
    "mathematicsskill": 6,
    "artisticskill": 3,
    "computerskill": 7,
    "programmingskill": 5,
    "graphicsprogrammingskill": 1,
    "hciskill": 4,
    "evaluationskill": 4,
    "communicationskill": 8,
    "collaborationskill": 9,
    "repositoryskill": 7
  },
  {
    "Timestamp": "2019-01-15T22:07:05.530Z",
    "name": "Amycus Carrow",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Rendering algorithms, game engine development and utility",
    "expectations": "Some modern visualization methods, use tools or on web pages",
    "visualizationskill": 5,
    "statisticalskill": 6,
    "mathematicsskill": 5,
    "artisticskill": 6,
    "computerskill": 9,
    "programmingskill": 7,
    "graphicsprogrammingskill": 8,
    "hciskill": 2,
    "evaluationskill": 1,
    "communicationskill": 7,
    "collaborationskill": 7,
    "repositoryskill": 9
  },
  {
    "Timestamp": "2019-01-16T00:30:41.132Z",
    "name": "Reginald Cattermole",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Social interaction, Swimming, Video games, Programming, food. ",
    "expectations": "There have been several instances in different courses that teaches about the ability to acquire and structure data, but from the course, I wish to learn the ability to actually present it in a manner that is both intuitive and efficient. I think it is a very good skill to have in most fields within computer science today, since you will very likely be dealing with a lot of abstraction. Abstracting away unnecessary information while still keeping it wholesome is a very good ability to have. ",
    "visualizationskill": 4,
    "statisticalskill": 5,
    "mathematicsskill": 7,
    "artisticskill": 3,
    "computerskill": 9,
    "programmingskill": 9,
    "graphicsprogrammingskill": 1,
    "hciskill": 4,
    "evaluationskill": 2,
    "communicationskill": 10,
    "collaborationskill": 7,
    "repositoryskill": 10
  },
  {
    "Timestamp": "2019-01-16T00:49:30.895Z",
    "name": "Mary Cattermole ",
    "major": "Computer Science, Business Administration",
    "pursuingDegree": "Master in Science",
    "interests": "Travel",
    "expectations": "I want to learn the way to be D3 super master, and to go through challenging project with my friends ovvvvernight!",
    "visualizationskill": 8,
    "statisticalskill": 8,
    "mathematicsskill": 7,
    "artisticskill": 5,
    "computerskill": 9,
    "programmingskill": 8,
    "graphicsprogrammingskill": 2,
    "hciskill": 1,
    "evaluationskill": 2,
    "communicationskill": 5,
    "collaborationskill": 2,
    "repositoryskill": 8
  },
  {
    "Timestamp": "2019-01-16T08:41:30.520Z",
    "name": "Cho Chang ",
    "major": "Statistics, Systems Engineering and Management",
    "pursuingDegree": "Bachelor in Engineering (in my home institute)",
    "interests": "Listening to music",
    "expectations": "Learn the method of presenting ideas to end users when giving out presentation.",
    "visualizationskill": 2,
    "statisticalskill": 3,
    "mathematicsskill": 4,
    "artisticskill": 1,
    "computerskill": 3,
    "programmingskill": 1,
    "graphicsprogrammingskill": 1,
    "hciskill": 2,
    "evaluationskill": 3,
    "communicationskill": 9,
    "collaborationskill": 9,
    "repositoryskill": 1
  },
  {
    "Timestamp": "2019-01-16T09:04:56.547Z",
    "name": "Penelope Clearwater ",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "I am interested in all things visual. Love movies and especially video games. Got really interested in augmented reality from the Multimodal Interactions. Like web-developing in javascript with frameworks such as React and Angular. Excited to work with D3.js. ",
    "expectations": "I expect to be an expert in D3.js and generally get a better idea and foundation on visualizing information. Like, if I get a dataset, hopefully I will have a better mindset on how to visualize it.",
    "visualizationskill": 4,
    "statisticalskill": 2,
    "mathematicsskill": 3,
    "artisticskill": 3,
    "computerskill": 8,
    "programmingskill": 3,
    "graphicsprogrammingskill": 1,
    "hciskill": 5,
    "evaluationskill": 2,
    "communicationskill": 9,
    "collaborationskill": 8,
    "repositoryskill": 7
  },
  {
    "Timestamp": "2019-01-16T09:31:54.345Z",
    "name": "Michael Corner",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "Music, sports, photography, games",
    "expectations": "How to effectively display information and make it look interesting while being interactive.",
    "visualizationskill": 5,
    "statisticalskill": 4,
    "mathematicsskill": 6,
    "artisticskill": 5,
    "computerskill": 7,
    "programmingskill": 5,
    "graphicsprogrammingskill": 4,
    "hciskill": 4,
    "evaluationskill": 4,
    "communicationskill": 6,
    "collaborationskill": 6,
    "repositoryskill": 6
  },
  {
    "Timestamp": "2019-01-16T09:32:55.382Z",
    "name": "Vincent Crabbe",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "I really enjoy my studies and I'm also running a digital agency besides the studies from 2,5 years back. When I don't enjoy studying or working I like to travel, meet new people, have beers with friends and be with my family.",
    "expectations": "Possibly testing out working with new technologies and being able to motivate different design choices when it comes to visualizing data. The basics of what visualizations works best in what situations etc.",
    "visualizationskill": 5,
    "statisticalskill": 2,
    "mathematicsskill": 2,
    "artisticskill": 7,
    "computerskill": 9,
    "programmingskill": 6,
    "graphicsprogrammingskill": 2,
    "hciskill": 6,
    "evaluationskill": 7,
    "communicationskill": 10,
    "collaborationskill": 9,
    "repositoryskill": 9
  },
  {
    "Timestamp": "2019-01-16T09:41:03.490Z",
    "name": "Colin Creevey",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "UX design, Wireframing, Programming (C, Obj-C, C++, Python), Gaming, Reading up on tech news",
    "expectations": "I wish to learn how to effectively visualise abstract data so as create modular interfaces that users can use to gather meaningful insights. This would greatly hep me with my current line of work as UX consultant ",
    "visualizationskill": 7,
    "statisticalskill": 3,
    "mathematicsskill": 6,
    "artisticskill": 8,
    "computerskill": 10,
    "programmingskill": 8,
    "graphicsprogrammingskill": 2,
    "hciskill": 6,
    "evaluationskill": 4,
    "communicationskill": 5,
    "collaborationskill": 2,
    "repositoryskill": 9
  },
  {
    "Timestamp": "2019-01-16T09:46:51.650Z",
    "name": "Fleur Delacour ",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "I'm interested in graphics, UX-UI, web dev ",
    "expectations": "I expect to learn how to take seemingly ordinary datasets and through visualisation make them extraordinary and insightful.",
    "visualizationskill": 4,
    "statisticalskill": 3,
    "mathematicsskill": 2,
    "artisticskill": 7,
    "computerskill": 10,
    "programmingskill": 3,
    "graphicsprogrammingskill": 1,
    "hciskill": 5,
    "evaluationskill": 6,
    "communicationskill": 9,
    "collaborationskill": 9,
    "repositoryskill": 5
  },
  {
    "Timestamp": "2019-01-16T09:56:55.418Z",
    "name": "Amos Diggory",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Training ",
    "expectations": "I'm expecting to learn in what way you should present data and the different good ways you can present data. ",
    "visualizationskill": 2,
    "statisticalskill": 4,
    "mathematicsskill": 5,
    "artisticskill": 3,
    "computerskill": 7,
    "programmingskill": 4,
    "graphicsprogrammingskill": 1,
    "hciskill": 2,
    "evaluationskill": 1,
    "communicationskill": 6,
    "collaborationskill": 7,
    "repositoryskill": 7
  },
  {
    "Timestamp": "2019-01-16T10:03:23.927Z",
    "name": "Albus Dumbledore",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "I am a musician beside my studies at KTH.",
    "expectations": "I hope to learn more about efficient visualization methods and then practice these in the projects. I'm not exactly sure how I'll use the knowledge, maybe in my future profession?",
    "visualizationskill": 3,
    "statisticalskill": 6,
    "mathematicsskill": 6,
    "artisticskill": 3,
    "computerskill": 6,
    "programmingskill": 4,
    "graphicsprogrammingskill": 2,
    "hciskill": 3,
    "evaluationskill": 4,
    "communicationskill": 6,
    "collaborationskill": 8,
    "repositoryskill": 6
  },
  {
    "Timestamp": "2019-01-16T10:15:16.935Z",
    "name": "Seamus Finnigan",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Programming, Rocket League, Music",
    "expectations": "Cool visualizations",
    "visualizationskill": 1,
    "statisticalskill": 3,
    "mathematicsskill": 5,
    "artisticskill": 1,
    "computerskill": 9,
    "programmingskill": 7,
    "graphicsprogrammingskill": 8,
    "hciskill": 3,
    "evaluationskill": 2,
    "communicationskill": 1,
    "collaborationskill": 9,
    "repositoryskill": 8
  },
  {
    "Timestamp": "2019-01-16T10:27:06.731Z",
    "name": "Marcus Flint",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Programming, video games, anything computer-related ",
    "expectations": "I expect to learn how to present different type of data in the best way possible",
    "visualizationskill": 6,
    "statisticalskill": 2,
    "mathematicsskill": 2,
    "artisticskill": 5,
    "computerskill": 8,
    "programmingskill": 7,
    "graphicsprogrammingskill": 8,
    "hciskill": 6,
    "evaluationskill": 2,
    "communicationskill": 5,
    "collaborationskill": 5,
    "repositoryskill": 6
  },
  {
    "Timestamp": "2019-01-16T10:34:14.248Z",
    "name": "Filius Flitwick ",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "I love music. I play a few instruments. Photography and film as well. Any creative channels",
    "expectations": "I expect to learn how to effectively communicate data. Improve my design  process and discover more technologies.",
    "visualizationskill": 3,
    "statisticalskill": 5,
    "mathematicsskill": 6,
    "artisticskill": 7,
    "computerskill": 9,
    "programmingskill": 1,
    "graphicsprogrammingskill": 1,
    "hciskill": 1,
    "evaluationskill": 7,
    "communicationskill": 7,
    "collaborationskill": 9,
    "repositoryskill": 4
  },
  {
    "Timestamp": "2019-01-16T10:49:34.202Z",
    "name": "Cornelius Fudge",
    "major": "Systems,  Robotics and Control",
    "pursuingDegree": "Master in Science",
    "interests": "My educational interests are mainly centered around autonomous systems. I like the idea of robots autonomously interacting with their environment. Thus, areas such as computer vision and machine learning is what really interests me. Apart from that I really enjoy spending time in nature and taking photos. I also enjoy doing a lot of sports and am constantly trying to improve my Swedish..",
    "expectations": "I usually work with a lot of data that is at times really difficult to comprehend due to a lack of intuitive insights into what the data represents. I expect to learn something about ways to visualize data in a way that it allows for an intuitive understanding of what the data represents even in complicated applications. I expect to use the knowledge from this course in presentations and projects centered around robots that will allow me to comprehensively visualize the complex mathematical stuff going on in the background.",
    "visualizationskill": 2,
    "statisticalskill": 6,
    "mathematicsskill": 6,
    "artisticskill": 2,
    "computerskill": 4,
    "programmingskill": 4,
    "graphicsprogrammingskill": 2,
    "hciskill": 3,
    "evaluationskill": 1,
    "communicationskill": 6,
    "collaborationskill": 6,
    "repositoryskill": 5
  },
  {
    "Timestamp": "2019-01-16T11:16:55.783Z",
    "name": "Gellert Grindelwald ",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Cooking and sports.",
    "expectations": "How to present data in a Clear/fun way",
    "visualizationskill": 5,
    "statisticalskill": 3,
    "mathematicsskill": 4,
    "artisticskill": 6,
    "computerskill": 6,
    "programmingskill": 3,
    "graphicsprogrammingskill": 1,
    "hciskill": 2,
    "evaluationskill": 5,
    "communicationskill": 7,
    "collaborationskill": 8,
    "repositoryskill": 4
  },
  {
    "Timestamp": "2019-01-16T11:43:13.664Z",
    "name": "Godric Gryffindor ",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Programming, Music/Guitar, Gaming",
    "expectations": "I expect to learn how to visualize data in an intriguing and user-friendly manner. This is a skill i aim to use in my future work and projects when coding websites and GUI's",
    "visualizationskill": 2,
    "statisticalskill": 5,
    "mathematicsskill": 7,
    "artisticskill": 3,
    "computerskill": 4,
    "programmingskill": 5,
    "graphicsprogrammingskill": 3,
    "hciskill": 3,
    "evaluationskill": 1,
    "communicationskill": 10,
    "collaborationskill": 8,
    "repositoryskill": 5
  },
  {
    "Timestamp": "2019-01-16T11:48:38.298Z",
    "name": "Rubeus Hagrid ",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Photography, politics, news",
    "expectations": "How to create context from raw data, highlighting hidden connections, making information more usable and understandable. ",
    "visualizationskill": 3,
    "statisticalskill": 4,
    "mathematicsskill": 4,
    "artisticskill": 1,
    "computerskill": 7,
    "programmingskill": 6,
    "graphicsprogrammingskill": 1,
    "hciskill": 3,
    "evaluationskill": 2,
    "communicationskill": 8,
    "collaborationskill": 6,
    "repositoryskill": 7
  },
  {
    "Timestamp": "2019-01-16T11:49:58.200Z",
    "name": "Rolanda Hooch ",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Software development, reading, gaming",
    "expectations": "Vast number of alternatives to present the data interactively. I want to use it for building my portfolio.",
    "visualizationskill": 5,
    "statisticalskill": 4,
    "mathematicsskill": 5,
    "artisticskill": 8,
    "computerskill": 9,
    "programmingskill": 8,
    "graphicsprogrammingskill": 5,
    "hciskill": 8,
    "evaluationskill": 7,
    "communicationskill": 10,
    "collaborationskill": 5,
    "repositoryskill": 9
  },
  {
    "Timestamp": "2019-01-16T12:22:34.692Z",
    "name": "Helga Hufflepuff",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "Any type of development interests me a lot. I also love teaching others and making products which other people appreciate",
    "expectations": "How to make pretty information visualizations which conveys information in a really clear way to anyone, it should also be fun to interact with. Today I have no idea how to do anything close to this, so any step in this direction is a welcomed one!",
    "visualizationskill": 1,
    "statisticalskill": 3,
    "mathematicsskill": 5,
    "artisticskill": 3,
    "computerskill": 7,
    "programmingskill": 4,
    "graphicsprogrammingskill": 1,
    "hciskill": 3,
    "evaluationskill": 4,
    "communicationskill": 9,
    "collaborationskill": 4,
    "repositoryskill": 6
  },
  {
    "Timestamp": "2019-01-16T13:08:58.943Z",
    "name": "Hermione Granger",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Drawing",
    "expectations": "I want to be able to have different theories and methods I can evaluate between when choosing visualization technique in the future. For an example, how to visualize three data variables in a 2D plot.",
    "visualizationskill": 2,
    "statisticalskill": 2,
    "mathematicsskill": 4,
    "artisticskill": 8,
    "computerskill": 9,
    "programmingskill": 8,
    "graphicsprogrammingskill": 2,
    "hciskill": 6,
    "evaluationskill": 4,
    "communicationskill": 7,
    "collaborationskill": 8,
    "repositoryskill": 9
  },
  {
    "Timestamp": "2019-01-16T13:38:34.738Z",
    "name": "Igor Karkaroff ",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "",
    "expectations": "The theory and methods to develop a information chart",
    "visualizationskill": 7,
    "statisticalskill": 6,
    "mathematicsskill": 6,
    "artisticskill": 3,
    "computerskill": 7,
    "programmingskill": 7,
    "graphicsprogrammingskill": 4,
    "hciskill": 6,
    "evaluationskill": 6,
    "communicationskill": 7,
    "collaborationskill": 6,
    "repositoryskill": 6
  },
  {
    "Timestamp": "2019-01-16T14:17:36.236Z",
    "name": "Viktor Krum",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Sports and video games",
    "expectations": "I want to learn how to properly visualize information. I might want to work with something about it or use the knowledge in my own projects, such as a website.",
    "visualizationskill": 6,
    "statisticalskill": 4,
    "mathematicsskill": 4,
    "artisticskill": 4,
    "computerskill": 8,
    "programmingskill": 4,
    "graphicsprogrammingskill": 3,
    "hciskill": 4,
    "evaluationskill": 4,
    "communicationskill": 10,
    "collaborationskill": 6,
    "repositoryskill": 7
  },
  {
    "Timestamp": "2019-01-16T14:18:02.245Z",
    "name": "Silvanus Kettleburn ",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "I have a BFA in electronic media, so I enjoy art a lot: Exhibitions, paintings, drawings and all the other things in that world. I also like to exercise, I ride my bicycle (not in the snow), do indoor-rowing and basic exercise.  Used to work in a huge library and learned to love old books and manuscripts with forgotten stories. I have always liked programming and therefore decided to study my masters in order to explore more and improve my skills. ",
    "expectations": "I want know get the knowledge to take proper decisions either collecting data and visualizing it. I would prefer to practice it and do stuff from little to big projects. I would like use it in art installations, graphic design and web pages initially, but I would like to go beyond that. ",
    "visualizationskill": 4,
    "statisticalskill": 2,
    "mathematicsskill": 2,
    "artisticskill": 9,
    "computerskill": 8,
    "programmingskill": 3,
    "graphicsprogrammingskill": 2,
    "hciskill": 2,
    "evaluationskill": 3,
    "communicationskill": 9,
    "collaborationskill": 8,
    "repositoryskill": 5
  },
  {
    "Timestamp": "2019-01-16T15:25:49.272Z",
    "name": "Bellatrix Lestrange",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Creating cool shit, mostly on some sort of a computer.",
    "expectations": "Ways of displaying information in a way that makes it easy to take in, for both questions",
    "visualizationskill": 3,
    "statisticalskill": 5,
    "mathematicsskill": 6,
    "artisticskill": 3,
    "computerskill": 9,
    "programmingskill": 7,
    "graphicsprogrammingskill": 5,
    "hciskill": 4,
    "evaluationskill": 5,
    "communicationskill": 7,
    "collaborationskill": 8,
    "repositoryskill": 8
  },
  {
    "Timestamp": "2019-01-16T15:47:25.261Z",
    "name": "Neville Longbottom",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Games.",
    "expectations": "How to create nice visuals using programming. Expect to use it to create nice products in the future.",
    "visualizationskill": 3,
    "statisticalskill": 5,
    "mathematicsskill": 5,
    "artisticskill": 3,
    "computerskill": 8,
    "programmingskill": 6,
    "graphicsprogrammingskill": 3,
    "hciskill": 5,
    "evaluationskill": 7,
    "communicationskill": 10,
    "collaborationskill": 10,
    "repositoryskill": 9
  },
  {
    "Timestamp": "2019-01-16T15:55:09.536Z",
    "name": "Xenophilius Lovegood ",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Video games and music",
    "expectations": "I expect to learn about how to visualize information in a way that is easy to understand",
    "visualizationskill": 5,
    "statisticalskill": 3,
    "mathematicsskill": 3,
    "artisticskill": 7,
    "computerskill": 9,
    "programmingskill": 7,
    "graphicsprogrammingskill": 3,
    "hciskill": 6,
    "evaluationskill": 7,
    "communicationskill": 7,
    "collaborationskill": 5,
    "repositoryskill": 4
  },
  {
    "Timestamp": "2019-01-16T16:11:12.672Z",
    "name": "Remus Lupin",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "Working out at the gym and playing video games. ",
    "expectations": "More about java script and its visual frameworks such as D3.js and also how to present data in an intuitive manner. Maybe at a future workplace. ",
    "visualizationskill": 3,
    "statisticalskill": 4,
    "mathematicsskill": 4,
    "artisticskill": 4,
    "computerskill": 7,
    "programmingskill": 5,
    "graphicsprogrammingskill": 1,
    "hciskill": 3,
    "evaluationskill": 2,
    "communicationskill": 8,
    "collaborationskill": 8,
    "repositoryskill": 6
  },
  {
    "Timestamp": "2019-01-16T16:41:21.215Z",
    "name": "Draco Malfoy",
    "major": "Computer Science, Human-Computer Interaction",
    "pursuingDegree": "Master in Science",
    "interests": "Computer games, reading, netflix, watching Twitch streams, beer",
    "expectations": "To learn tools to display information further than in an infograph.",
    "visualizationskill": 4,
    "statisticalskill": 1,
    "mathematicsskill": 2,
    "artisticskill": 1,
    "computerskill": 9,
    "programmingskill": 9,
    "graphicsprogrammingskill": 3,
    "hciskill": 8,
    "evaluationskill": 9,
    "communicationskill": 9,
    "collaborationskill": 10,
    "repositoryskill": 10
  },
  {
    "Timestamp": "2019-01-16T16:49:09.006Z",
    "name": "Ernie Macmillan",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "Sports of all kinds, computer games, programming (i suppose?)",
    "expectations": "General good practices in info vis.\nTools and utilities.\nWant to do something fun and creative where i put my old and newly aquired skills to use.\nWanna do an awesome project to put in my portfolio.\n",
    "visualizationskill": 3,
    "statisticalskill": 6,
    "mathematicsskill": 4,
    "artisticskill": 2,
    "computerskill": 8,
    "programmingskill": 5,
    "graphicsprogrammingskill": 2,
    "hciskill": 7,
    "evaluationskill": 7,
    "communicationskill": 10,
    "collaborationskill": 9,
    "repositoryskill": 6
  },
  {
    "Timestamp": "2019-01-16T17:13:47.093Z",
    "name": "Minerva McGonagall",
    "major": "Human-Computer Interaction, Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "I like to create and design pretty things",
    "expectations": "How to visualise things in a better way and also new frameworks and tools for doing so",
    "visualizationskill": 3,
    "statisticalskill": 1,
    "mathematicsskill": 4,
    "artisticskill": 6,
    "computerskill": 7,
    "programmingskill": 2,
    "graphicsprogrammingskill": 1,
    "hciskill": 4,
    "evaluationskill": 5,
    "communicationskill": 9,
    "collaborationskill": 6,
    "repositoryskill": 1
  },
  {
    "Timestamp": "2019-01-16T17:24:56.475Z",
    "name": "Cormac McLaggen",
    "major": "Data Science",
    "pursuingDegree": "Master in Science",
    "interests": "Art has always fascinated me  though I am not an artist but I feel that creative minds always look at things in a very different way. Looking at the data and visualizing it in a unique way is interesting as well as exciting . \nI love to cook .It is something that makes me happy . I become a creative person whenever i cook.",
    "expectations": "I expect to see data in a different way .I am pretty excited about this course  and its my area of interest .I feel this course will help me a lot .",
    "visualizationskill": 4,
    "statisticalskill": 5,
    "mathematicsskill": 4,
    "artisticskill": 6,
    "computerskill": 5,
    "programmingskill": 6,
    "graphicsprogrammingskill": 4,
    "hciskill": 2,
    "evaluationskill": 5,
    "communicationskill": 7,
    "collaborationskill": 6,
    "repositoryskill": 4
  },
  {
    "Timestamp": "2019-01-16T17:41:40.494Z",
    "name": "Graham Montague",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "I finished my bachelor's a couple of years ago and started working right away in the industry as a UI Engineer consultant focusing mainly on web technologies. I've also taken on some jobs before getting my degree but most were freelancing or volunteering. Right now I'm interested in meeting new people and sharpening my HCI-related skills. Some of my hobbies include playing music, coding, gaming, and reading.",
    "expectations": "Best practices when dealing with data visualization, do, don'ts, etc. Common tools, or at least the notion that they exist, to use professionally. Practical knowledge that can be applied as soon as the course is over.",
    "visualizationskill": 3,
    "statisticalskill": 5,
    "mathematicsskill": 7,
    "artisticskill": 3,
    "computerskill": 9,
    "programmingskill": 8,
    "graphicsprogrammingskill": 3,
    "hciskill": 5,
    "evaluationskill": 7,
    "communicationskill": 8,
    "collaborationskill": 10,
    "repositoryskill": 9
  },
  {
    "Timestamp": "2019-01-16T18:44:29.638Z",
    "name": "Theodore Nott",
    "major": "Human-Computer Interaction, Media Technology",
    "pursuingDegree": "Master in interactive media technology",
    "interests": "I like art and paint a lot. I have worked as a UX designer and love to create beautiful things such as logos and prototypes. I do also like front-end programming.",
    "expectations": "I love rhetoric and being able to influence people. I expect to be able to influence people to an even greater level with the help of visualization.",
    "visualizationskill": 1,
    "statisticalskill": 1,
    "mathematicsskill": 5,
    "artisticskill": 10,
    "computerskill": 8,
    "programmingskill": 2,
    "graphicsprogrammingskill": 1,
    "hciskill": 3,
    "evaluationskill": 7,
    "communicationskill": 10,
    "collaborationskill": 10,
    "repositoryskill": 1
  },
  {
    "Timestamp": "2019-01-16T19:01:24.152Z",
    "name": "Garrick Ollivander ",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "",
    "expectations": "Honestly i expect to learn how to make computer graphics that look cool.",
    "visualizationskill": 3,
    "statisticalskill": 3,
    "mathematicsskill": 4,
    "artisticskill": 3,
    "computerskill": 9,
    "programmingskill": 8,
    "graphicsprogrammingskill": 5,
    "hciskill": 5,
    "evaluationskill": 3,
    "communicationskill": 7,
    "collaborationskill": 7,
    "repositoryskill": 1
  },
  {
    "Timestamp": "2019-01-16T19:10:28.464Z",
    "name": "Pansy Parkinson",
    "major": "Computer Science",
    "pursuingDegree": "Master in Science",
    "interests": "",
    "expectations": "Representing data in a way that gives a good overview of it. Will probably be useful to know almost anywhere as so much depends on studying all the data collected.",
    "visualizationskill": 7,
    "statisticalskill": 4,
    "mathematicsskill": 4,
    "artisticskill": 7,
    "computerskill": 8,
    "programmingskill": 8,
    "graphicsprogrammingskill": 6,
    "hciskill": 7,
    "evaluationskill": 4,
    "communicationskill": 7,
    "collaborationskill": 8,
    "repositoryskill": 7
  },
  {
    "Timestamp": "2019-01-16T19:51:25.307Z",
    "name": "Peter Pettigrew ",
    "major": "Data Science",
    "pursuingDegree": "Master in Science",
    "interests": "Travelling. Fashion.",
    "expectations": "Learn how to visualise data in a proper way and give more useful information. By prating and learning from the teachers and other students.",
    "visualizationskill": 5,
    "statisticalskill": 7,
    "mathematicsskill": 8,
    "artisticskill": 6,
    "computerskill": 8,
    "programmingskill": 8,
    "graphicsprogrammingskill": 6,
    "hciskill": 4,
    "evaluationskill": 7,
    "communicationskill": 10,
    "collaborationskill": 10,
    "repositoryskill": 8
  },
  {
    "Timestamp": "2019-01-16T20:33:10.148Z",
    "name": "Antioch Peverell",
    "major": "Computer Science, Media Technology, Mathematics, Statistics, Machine Learning",
    "pursuingDegree": "Master in Science",
    "interests": "I love to watch and play football. I also like video games and how they are made. ",
    "expectations": "Since i'm always working with data, i'm really interested in the way of presenting it. With this course, I hope to be able to interpret some graphs more easily and to make them.",
    "visualizationskill": 1,
    "statisticalskill": 6,
    "mathematicsskill": 6,
    "artisticskill": 2,
    "computerskill": 8,
    "programmingskill": 3,
    "graphicsprogrammingskill": 1,
    "hciskill": 2,
    "evaluationskill": 3,
    "communicationskill": 6,
    "collaborationskill": 6,
    "repositoryskill": 5
  },
  {
    "Timestamp": "2019-01-16T20:53:35.054Z",
    "name": "Irma Pince",
    "major": "Computer Science, Human-Computer Interaction",
    "pursuingDegree": "Master in Science",
    "interests": "I like to work with more frontend-oriented technology, and in particular with solutions where I get to understand how to create something that has a high degree of usability(i.e. my interest in HCI in general).\n\nIn terms of other hobbies, I have a keen interest in films as well as football. ",
    "expectations": "I am interested in learning more about information visualization as I think the importance of it is growing rapidly as more and more data is available.\n\nI expect to get more hands-on experience with creating visuals related to information visualization. I'm not sure if there are any specific \"good-practices\"(I don't expect it to) but I am eager to see what research material on the topic also says.\n\nI believe I might be able to use what I've learned in a potential future career choice. For instance if I want to learn more about Business Intelligence this could be valuable. ",
    "visualizationskill": 1,
    "statisticalskill": 5,
    "mathematicsskill": 7,
    "artisticskill": 2,
    "computerskill": 9,
    "programmingskill": 6,
    "graphicsprogrammingskill": 1,
    "hciskill": 6,
    "evaluationskill": 7,
    "communicationskill": 7,
    "collaborationskill": 8,
    "repositoryskill": 4
  },
  {
    "Timestamp": "2019-01-16T21:49:22.686Z",
    "name": "Sturgis Podmore ",
    "major": "Computer Science, Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "I'm a big data engineer (or full stack engineer) and a seasonal entrepreneur, working with industry for more than 5 years. If I'm not an engineer then I would be an adventurer. I love expedition, trekking, mountaineering, skiing, last but not the least badminton. I collect adventures' memories with gadgets from action cameras to drone videography but I don't publish them. Hopefully will publish it one day. The next big thing in my bucket is to learn yacht sailing this summer. ",
    "expectations": "I already have a strong practical sense on modern data warehousing and rendering on Power BI. But this course will help me on the theoretical side of visualization. ",
    "visualizationskill": 6,
    "statisticalskill": 3,
    "mathematicsskill": 5,
    "artisticskill": 2,
    "computerskill": 10,
    "programmingskill": 10,
    "graphicsprogrammingskill": 8,
    "hciskill": 6,
    "evaluationskill": 3,
    "communicationskill": 10,
    "collaborationskill": 10,
    "repositoryskill": 10
  },
  {
    "Timestamp": "2019-01-16T22:56:21.299Z",
    "name": "Poppy Pomfrey ",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "",
    "expectations": "I would like to gather more information about how data should be structured and visualised in order to provide users with a fulfilling and insightful experience ",
    "visualizationskill": 5,
    "statisticalskill": 5,
    "mathematicsskill": 6,
    "artisticskill": 7,
    "computerskill": 8,
    "programmingskill": 8,
    "graphicsprogrammingskill": 8,
    "hciskill": 8,
    "evaluationskill": 4,
    "communicationskill": 7,
    "collaborationskill": 7,
    "repositoryskill": 9
  },
  {
    "Timestamp": "2019-01-17T08:09:45.132Z",
    "name": "Harry Potter ",
    "major": "Media Technology",
    "pursuingDegree": "Master in Science",
    "interests": "",
    "expectations": "Ledsen how to visualize heavy data in a intuitive way ",
    "visualizationskill": 7,
    "statisticalskill": 2,
    "mathematicsskill": 4,
    "artisticskill": 10,
    "computerskill": 8,
    "programmingskill": 5,
    "graphicsprogrammingskill": 4,
    "hciskill": 8,
    "evaluationskill": 9,
    "communicationskill": 8,
    "collaborationskill": 8,
    "repositoryskill": 7
  }
]